env:
  browser: true
  es2021: true
  jest: true
extends:
  - "plugin:react/recommended"
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  {
    semi: ["error", "never"],
    react/react-in-jsx-scope: off,
    global-require: off,
    eslintmax-len: off,
    jsx-props-no-spreading: off,
    react/prop-types: off,
    react/jsx-filename-extension: ["error", { extensions: [".jsx", ".js"] }],
    import/prefer-default-export: off,
    no-unused-expressions: ["error", { allowTaggedTemplates: true }],
    jsx-a11y/label-has-associated-control: off,
    jsx-a11y/click-events-have-key-events: off,
    jsx-a11y/no-static-element-interactions: off,
    max-len: off,
    react/jsx-props-no-spreading: off,
    import/no-named-as-default: off,
    import/no-named-as-default-member: off,
    react/no-unescaped-entities: off,
    react/destructuring-assignment: off,
    react/jsx-no-bind: off,
  }
